# NUMPY TUTORIAL

In [2]:
import numpy

In [3]:
numpy.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [4]:
numpy.array([11,12,13,14,15])

array([11, 12, 13, 14, 15])

In [5]:
import numpy as np

In [6]:
a=np.array([90,92,93,88,55,76,12,35])

In [7]:
a

array([90, 92, 93, 88, 55, 76, 12, 35])

In [8]:
a.shape

(8,)

In [9]:
b=np.array([10,20,30,40,50,60,70,80,90,100])

In [10]:
b

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [11]:
b.shape

(10,)

In [12]:
a=np.array([[1,2],[3,4]])

In [13]:
a

array([[1, 2],
       [3, 4]])

In [14]:
a.shape

(2, 2)

In [15]:
b=np.array([[11,12],[13,14],[15,16]])

In [16]:
b

array([[11, 12],
       [13, 14],
       [15, 16]])

In [17]:
b.shape

(3, 2)

In [18]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
c.shape

(3, 3)

In [21]:
d=np.array([[50,51,52,53],[54,55,56,57]])

In [22]:
d

array([[50, 51, 52, 53],
       [54, 55, 56, 57]])

In [23]:
d.shape

(2, 4)

In [24]:
e=np.array([[50,52,53,58,56],[65,63,69,65,68],[85,87,89,81,82],[45,46,42,41,43],[78,75,76,71,72]])

In [25]:
e

array([[50, 52, 53, 58, 56],
       [65, 63, 69, 65, 68],
       [85, 87, 89, 81, 82],
       [45, 46, 42, 41, 43],
       [78, 75, 76, 71, 72]])

In [26]:
e.shape

(5, 5)

In [27]:
g=np.array([[4,6],[8,3],[9,5]])
g

array([[4, 6],
       [8, 3],
       [9, 5]])

In [28]:
g.shape

(3, 2)

In [29]:
g.reshape(2,3)

array([[4, 6, 8],
       [3, 9, 5]])

In [30]:
b=np.array([[78,90],[22,33]])
b

array([[78, 90],
       [22, 33]])

In [31]:
b.min()

22

In [32]:
b.max()

90

In [33]:
b.shape

(2, 2)

In [34]:
#gives the count of number of elements
b.size

4

In [35]:
#gives the number o bytes/memory occupied by each element
b.itemsize

4

In [36]:
b.dtype

dtype('int32')

In [37]:
#gives the memory address
b.data

In [38]:
b=np.array([[1,2],[3,4],[5,6]],dtype='float64')
#c1=np.array([[1,2],[3,4],[5,6]])

b
#c1

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [39]:
b.dtype

dtype('float64')

In [40]:
#number of dimension
b.ndim

2

In [41]:
#gives number of bytes : it is float datatypehence it takes 8 bytes to store the data
b.itemsize

8

In [42]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [43]:
x=np.arange(15)

In [44]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [45]:
b=x.reshape(3,5)

In [46]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
b=x.reshape(5,3)

In [48]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [49]:
x=np.arange(25)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [50]:
b=x.reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
b=np.arange(35).reshape(5,7)
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [52]:
b.shape

(5, 7)

In [53]:
b.ndim # 2 stands for rows and columns

2

In [54]:
b.dtype

dtype('int32')

In [55]:
type(b)

numpy.ndarray

In [56]:
import numpy as np
b=np.array([[1.5,2,3],[4,5,6]],dtype='float32')

In [57]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

In [58]:
rb=np.array([[34,78,89],[22,33,77]])
rb

array([[34, 78, 89],
       [22, 33, 77]])

In [59]:
# ravel operatiom where you can convert one numpy array into a single row i.e ravel
print(rb.ravel())

[34 78 89 22 33 77]


In [60]:
import numpy as np
b=np.array([[1.5,2,3],[4,5,6]],dtype='int32')
b

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [64]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
#(start,end,skip or jump)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [66]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [67]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# BROADCASTING IN NUMPY

In [68]:
a=np.array([1.0,2.0,3.0])
b=np.array([2.0,2.0,2.0])
a*b

array([2., 4., 6.])

In [69]:
a=np.array([1.0,2.0,3.0])
b=2.0
a*b

array([2., 4., 6.])

In [70]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [71]:
c=a-b
print(c)

[20 29 38 47]


In [72]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [73]:
b=np.random.random([2,3])

In [74]:
b

array([[0.48092546, 0.72006664, 0.22250311],
       [0.06208531, 0.98866446, 0.62884491]])

In [75]:
c=np.ones([2,3])

In [76]:
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [77]:
d=b+c
d

array([[1.48092546, 1.72006664, 1.22250311],
       [1.06208531, 1.98866446, 1.62884491]])

# UNIVERSAL FUNCTION

In [78]:
B=np.arange(3)

In [79]:
B

array([0, 1, 2])

In [80]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [81]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [84]:
C=np.array([2,1,4])
np.add(B,C)

array([2, 2, 6])

# INDEXING , SLICING, AND ITERATING

In [88]:
b=np.arange(3)

In [89]:
b

array([0, 1, 2])